language: php
php:
- 7.2
- 7.3
dist: trusty
sudo: false
install: travis_retry composer install --no-interaction --prefer-source
script:
- touch database/database.sqlite
- php artisan migrate --force --env=testing
- vendor/bin/phpunit --verbose
notifications:
  slack:
    secure: fOtUxFrAm3QMRDo+S9ZbNc8JKxbMNZDWcBUYToZWRxKUV8AV41e6W3SN0vCEZgmtvtLT73LkZ9OSl9pCr1+3R9uctUukG/OoaYFmRg+4spyfYMJ8YhEPiDI/Rs0ibWcMtxYaacbYZ4yaFz35P7No0+Tq/mK2Jbq+9MkuauFqGzYdTzB30ZPPp7X3UgN9rgEW1ij89HLlD7sgknszze0AiaoR1p5kpkJ9VbKP9JyQ9cBWznbx4XsXIFfVYTlGEcxLyKsOvnPsav14C15SafBP8lDG5Qgvdn6eVnvfr0dWU+f6G0iLi62nFBxz2A6KgQ/tHrCoNF0cISgevQ4R6vv/o4xhyBqCNTrEE6HsZbOI+HUj4WrGkjH81+eQ5jjc3JPgQ+jHSkPFs1k4oTr4gkacIxWm7Y+dI4RFGzUvifuWB+5D1lWSTYnZa25J17mXNjIcAjaNFuj8MxWxeFBUiY91r9je06AG8TR+SKCC9wuhYf9DWMBOEOocRFXTW1hXFlVah+KNmFEo5gDbv08N1IcB3vdVxRdvu1vdqbaGcczCevAykFKdXHq4ZtuUCKHRyjVuNcXBBKlLHoPIN6dGBl4AXTMVpI92chA6jN4XsLWPqOzhKbWgnxKqw6ROmS/2OjM/HOokylqJ+ORJWCLQhaPA0MHlG4PPZdkeG6wTBccLD+M=
