language: php
php:
- 7.2
- 7.3
dist: trusty
sudo: false
install: travis_retry composer install --no-interaction --prefer-source
script:
- touch database/database.sqlite
- php artisan migrate --force --env=testing
- vendor/bin/phpunit --verbose
notifications:
  slack:
    rooms:
      secure: Tzh7ETbDwe+jIJY3omaaeqW7kuBfbynja8cJoGycFSEPZQagxigskzwU+rAuLXnG0bYR87oGbtDDcRQ2J+3R6CvWIw9L94ZxIRkpDr8BaVnnBG5Qx3T5iSa67reyrkM2+0mdKD9WukiquZOVQMOFr5eQg23hfUG1cORquHy2bN8dq0WQx87dSECE9tqPTNCehjgPEhUUO/yLSumR6Jwx0EOrVhgyf5vsyjjyBdRORP7/FGY+wh6vAcfwzb9ywyNBn9O/Rq8BfILBNRA6N5b/UYnzvWxNAUewSBVOR58MXMfv9CrzuoYGRxrH0bE9pZ2mLj4P3PZZv89F5k3ChWvYcJkt3maJa/EzAtiGY72NtaaXtzvSwINf7098eqr4OfWRPbOgBHMLUXKI2SE9fnRVMBT7G+5MHuaJ0fuXqE7SPZqdq+gh5OXt7ryGT0ogvcC5U3QPeyWhPjmOEXj5xqRIyQpycinWDxGVVp+AASfUDuRKr/O1WrvCZ7GOE/WIiso/2wI1KnQWiwvWjf7Y3rHQn4iEalzheqh9ZVEzSCc0HnAOGeA5IBVsa+GwGGP8Up+0hGKitYqfq3JihF1wCvXpisIAT351FAv7uYPjUpYMlsjmzqeZcnScG6iXsdfOwEbcIKleT43lNc9TZDAsOtOEHypazp/9LKk/hiJZp6vUxDs=
