language: php
php:
- 7.2
- 7.3
dist: trusty
sudo: false
install: travis_retry composer install --no-interaction --prefer-source
script:
- touch database/database.sqlite
- php artisan migrate --force --env=testing
- vendor/bin/phpunit --verbose
notifications:
  slack:
    secure: AP+znHRkN6NLB9dcaL9bRSQgP0TX/+DCpgXkAX4kt6c7lIuCtAq5sfshxpr7HaqOtj8HLkmBOpop8Jx+adAJxAFRznF20tYfX2yEMMLzuZh3txvsncoupMVKiXhURSwcCALRh7KCrOzYXe/dg9w5IijJzD669kwRXiKEMlktEFrMjBqlbID/r616KOt0xjmb9nou+itlA3NWuJdR2typZQjNXxwpZMEa6H1T8eqG+VlFnrQUr6m8mzrwcPmOoIzfEL4ox7OCTUPOKOufvGYloXW//UB3GeK7vWrtuwCBtfajwvWAH0BTsZsj74/fdTWUzSqY6Baf8414BlTEA3N8mRX1B9JXpxNe6yxnE/eZeHWfUDl81uXnP8A0jPvMiXdh/Wpo/0qrThLpcMaigZphGMXhzP2OWFvbM4QPlCum6wr1X/FhC2kWD7zRugKfKo6CehXL7Ilwybw3CQ2Q6v4nMKfEKfV7kte2S7Y2FoRasbYv9P1i9xTkZo2i3+0MKFWYVPQG6uDzQ1YB+tUdvA3PNJAS6ED51VL/R/kioI4AtYI9OzJFahKCwxHy/9628WloZWgDNsfds4rBMK0RiKx4lAyCSuviH0Kbf5nLN40jGOGVS+VJYvo06mJjvitODKwbbmtpYsUMhkrEkaRQtrNJyZL1cNWHk6/5fy6tNqHI+sw=
